### ISSUE TITLE
Demo site broken

### ISSUE THREAD

**Issue by Veve2** [kbond/ZenstruckFormBundle#39]
Hello,

First thanks for your bundle!
In [this page](http://zenstruck.com/projects/ZenstruckFormBundle), the link ["view demo"](http://sandbox.zenstruck.com/article/edit/random) is broken.

Could you maybe fix it?

Thanks by advance,

Veve

**Comment by kbond** [comment]
Thanks, fixed.

**Comment by pjuanda** [comment]
Hello there, is the demo site broken ?
I can't access  [demo site](http://sandbox.zenstruck.com/articles/edit/random)

Thanks

**Comment by kbond** [comment]
@pjuanda I no longer host the demo site but you can view the code for it here: https://github.com/kbond/sandbox
