### ISSUE TITLE
Little typo in ajax_entity example for the 'extra_data' option

### ISSUE THREAD

**Issue by Veve2** [kbond/ZenstruckFormBundle#40]
Hi again,

In the [AjaxEntityType](https://github.com/kbond/ZenstruckFormBundle#ajaxentitytype) example,

    // 'extra'          => array() // for adding extra data in the ajax request (only applicable when using repo_method)

Should be 

    // 'extra_data'          => array() // for adding extra data in the ajax request (only applicable when using repo_method)

Maybe also add this option to the [FormType options list](https://github.com/kbond/ZenstruckFormBundle#formtype-options)

BTW, how to use this `extra_data` parameter in my custom repo_method?

Veve

**Comment by kbond** [comment]
Thanks1

**Comment by Veve2** [comment]
Nice :)

Could you please hint me how to get the extra_data in my custom repo_method?
I've seen `q` is passed to the repository but I can't access the extra_data passed.
(Using ùse_controller`: true)

Veve

**Comment by kbond** [comment]
You are using the `repo_method` option as well?
